// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisVendas.Models;

namespace SisVendas.Migrations
{
    [DbContext(typeof(SisVendasContext))]
    [Migration("20190528212217_Classes")]
    partial class Classes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SisVendas.Models.Cliente", b =>
                {
                    b.Property<int>("IdCli")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DtNasc");

                    b.Property<string>("strNomeCli");

                    b.Property<string>("strSexo");

                    b.Property<string>("strUF");

                    b.HasKey("IdCli");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("SisVendas.Models.Departamento", b =>
                {
                    b.Property<int>("IdDepto")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("strDepto");

                    b.HasKey("IdDepto");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("SisVendas.Models.FormaPagto", b =>
                {
                    b.Property<int>("IdPagto")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("strPagto");

                    b.HasKey("IdPagto");

                    b.ToTable("FormaPagto");
                });

            modelBuilder.Entity("SisVendas.Models.Produto", b =>
                {
                    b.Property<int>("IdProd")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("douPreco");

                    b.Property<string>("strNomeProd");

                    b.HasKey("IdProd");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("SisVendas.Models.Vendas", b =>
                {
                    b.Property<int>("IdVenda")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("douVlVenda");

                    b.Property<DateTime>("dtVenda");

                    b.HasKey("IdVenda");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("SisVendas.Models.Vendedor", b =>
                {
                    b.Property<int>("IdVend")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("douSalBase");

                    b.Property<string>("strEmail");

                    b.Property<string>("strNomeVend");

                    b.HasKey("IdVend");

                    b.ToTable("Vendedor");
                });
#pragma warning restore 612, 618
        }
    }
}
